(() => {
  'use strict';
  const gate=document.getElementById('authGate'),app=document.getElementById('appointmentApp'),loginBtn=document.getElementById('loginBtn'),logoutBtn=document.getElementById('logoutBtn'),userEmail=document.getElementById('userEmail'),listEl=document.getElementById('appointmentList'),searchEl=document.getElementById('appointmentSearch'),statusEl=document.getElementById('statusFilter'),dateEl=document.getElementById('dateFilter'),serviceEl=document.getElementById('serviceFilter'),permissionNotice=document.getElementById('permissionNotice');
  let currentUser=null,appointments=[];
  const STATUS={new:['Yeni','status-new'],confirmed:['Onaylandı','status-confirmed'],completed:['Tamamlandı','status-completed'],cancelled:['İptal','status-cancelled']};
  const norm=v=>String(v||'').toLocaleLowerCase('tr-TR');
  function create(tag,attrs={},text=''){const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>{if(k==='class')n.className=v;else if(k.startsWith('data-'))n.setAttribute(k,v);else n[k]=v});if(text!=='')n.textContent=text;return n}
  async function authHeader(){const token=await currentUser?.jwt?.();return token?{Authorization:`Bearer ${token}`}:{}}function showApp(u){currentUser=u;userEmail.textContent=u?.email||'';gate.classList.add('hidden');app.classList.remove('hidden');loadAppointments()}function showLogin(){currentUser=null;app.classList.add('hidden');gate.classList.remove('hidden')}
  async function api(method='GET',body){const r=await fetch('/.netlify/functions/appointments',{method,headers:{...(await authHeader()),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,credentials:'same-origin',cache:'no-store'});if(r.status===403){permissionNotice.classList.remove('hidden');permissionNotice.textContent='Bu hesap randevu verilerini görüntüleme yetkisine sahip değil. Netlify ortam değişkenine ADMIN_EMAILS adıyla giriş yaptığınız e-posta adresini ekleyin ve yeniden dağıtım yapın.';throw new Error('Yetki yok')}if(!r.ok)throw new Error(await r.text());return r.json()}
  async function loadAppointments(){listEl.innerHTML='<div class="loading">Randevular hazırlanıyor…</div>';try{const d=await api();appointments=Array.isArray(d.appointments)?d.appointments:[];buildServiceFilter();render()}catch(e){console.error(e);listEl.innerHTML='<div class="empty">Randevular yüklenemedi. Yetki ve Netlify dağıtım ayarlarını kontrol edin.</div>'}}
  function buildServiceFilter(){const cur=serviceEl.value,services=[...new Set(appointments.map(x=>x.service).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'tr'));serviceEl.innerHTML='<option value="">Tüm hizmetler</option>';services.forEach(s=>serviceEl.appendChild(create('option',{value:s},s)));serviceEl.value=cur}
  function filteredItems(){const q=norm(searchEl.value).trim();return appointments.filter(x=>{if(statusEl.value&&x.status!==statusEl.value)return false;if(dateEl.value&&x.requestedDate!==dateEl.value)return false;if(serviceEl.value&&x.service!==serviceEl.value)return false;if(!q)return true;return norm([x.ownerName,x.phone,x.petName,x.species,x.service,x.requestedDate,x.requestedTime,x.note].join(' ')).includes(q)})}
  function updateCounts(){document.getElementById('countNew').textContent=appointments.filter(x=>x.status==='new').length;document.getElementById('countConfirmed').textContent=appointments.filter(x=>x.status==='confirmed').length;document.getElementById('countCompleted').textContent=appointments.filter(x=>x.status==='completed').length;document.getElementById('countTotal').textContent=appointments.length}
  function formatDate(v){if(!v)return'—';const d=new Date(v.includes('T')?v:`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('tr-TR',{day:'2-digit',month:'long',year:'numeric'})}
  function statusBadge(s){const [l,c]=STATUS[s]||STATUS.new;return create('span',{class:`status ${c}`},l)}function detailBox(l,v){const b=create('div',{class:'detail-box'});b.append(create('span',{class:'appointment-label'},l),create('span',{class:'appointment-value'},v||'—'));return b}
  function actionButton(label,status,cls=''){return create('button',{type:'button',class:`admin-btn ${cls}`,onclick:e=>{const id=e.currentTarget.closest('.appointment-card').dataset.id;updateAppointment(id,{status})}},label)}
  function renderCard(item){const card=create('article',{class:`appointment-card ${item.status==='new'?'is-new':''}`,'data-id':item.id}),summary=create('div',{class:'appointment-summary'}),lead=create('div');lead.append(create('h3',{},`${item.petName||'İsimsiz'} — ${item.ownerName||'Hasta sahibi'}`),create('p',{},`${item.species||'Tür belirtilmemiş'} • ${item.service||'Hizmet belirtilmemiş'}`));summary.append(lead);const db=create('div');db.append(create('span',{class:'appointment-label'},'Talep edilen tarih'),create('span',{class:'appointment-value'},formatDate(item.requestedDate)));summary.append(db);const tb=create('div');tb.append(create('span',{class:'appointment-label'},'Saat'),create('span',{class:'appointment-value'},item.requestedTime||'—'));summary.append(tb);const sb=create('div');sb.append(statusBadge(item.status));const toggle=create('button',{type:'button',class:'toggle-details'},'Detayları Aç');toggle.addEventListener('click',()=>{card.classList.toggle('open');toggle.textContent=card.classList.contains('open')?'Detayları Kapat':'Detayları Aç'});sb.append(document.createElement('br'),toggle);summary.append(sb);
    const details=create('div',{class:'appointment-details'}),grid=create('div',{class:'details-grid'});grid.append(detailBox('Telefon',item.phone),detailBox('Hayvan türü',item.species),detailBox('Hizmet',item.service),detailBox('Talep oluşturma',formatDate(item.createdAt)));details.append(grid);if(item.note){const n=detailBox('Hasta sahibi notu',item.note);n.style.marginTop='10px';details.append(n)}const noteWrap=create('div',{class:'note-wrap'});noteWrap.append(create('span',{class:'appointment-label'},'Klinik içi not'));const noteInput=create('textarea',{class:'note-input',rows:3});noteInput.value=item.internalNote||'';noteWrap.append(noteInput);details.append(noteWrap);const actions=create('div',{class:'appointment-actions'});actions.append(create('a',{class:'admin-btn primary',href:`tel:${item.phone||''}`},'Ara'),actionButton('Onaylandı','confirmed'),actionButton('Tamamlandı','completed'),actionButton('İptal','cancelled'));const save=create('button',{type:'button',class:'admin-btn'},'Notu Kaydet');save.addEventListener('click',()=>updateAppointment(item.id,{internalNote:noteInput.value}));actions.append(save);details.append(actions);card.append(summary,details);return card}
  function render(){updateCounts();const items=filteredItems();listEl.innerHTML='';if(!items.length){listEl.append(create('div',{class:'empty'},'Bu filtrelerle eşleşen randevu bulunamadı.'));return}items.forEach(x=>listEl.append(renderCard(x)))}
  async function updateAppointment(id,changes){try{const d=await api('PATCH',{id,...changes}),i=appointments.findIndex(x=>x.id===id);if(i>=0)appointments[i]=d.appointment;render()}catch(e){console.error(e);alert('Değişiklik kaydedilemedi.')}}
  [searchEl,statusEl,dateEl,serviceEl].forEach(el=>el?.addEventListener('input',render));loginBtn?.addEventListener('click',()=>window.netlifyIdentity?.open('login'));logoutBtn?.addEventListener('click',()=>window.netlifyIdentity?.logout());if(window.netlifyIdentity){window.netlifyIdentity.on('init',u=>u?showApp(u):showLogin());window.netlifyIdentity.on('login',u=>{showApp(u);window.netlifyIdentity.close()});window.netlifyIdentity.on('logout',showLogin);window.netlifyIdentity.init()}
})();
